const adminSide=document.querySelector('#admin .admin>aside');
const adminDash=document.querySelector('#admin .dash');
const adminHome=adminDash.innerHTML;
const adminStore=JSON.parse(localStorage.getItem('kitsune-admin-data')||'null')||{
  content:[['Astral Edge','Publicado'],['Mushoku Tensei T3','Publicado'],['Solo Leveling','Borrador']],
  users:[['josue@kitsune.com','Usuario','Activo'],['editor@kitsune.com','Programador','Activo'],['demo@kitsune.com','Usuario','Bloqueado']],
  jobs:[['astral-edge-s01e01.mp4','Completado','100%'],['mushoku-t3-trailer.mp4','Completado','100%'],['solo-leveling-s02e01.mp4','En cola','0%']],
  logs:[['Inicio de sesión administrativo','ADMIN','Ahora'],['Publicación de Mushoku Tensei','ADMIN','Hace 8 min'],['Cambio de rol de usuario','ADMIN','Ayer']]
};
function saveAdmin(){localStorage.setItem('kitsune-admin-data',JSON.stringify(adminStore))}
const head=t=>`<div class="admin-page-head"><div><small>KITSUNE CMS</small><h1>${t}</h1></div><button class="cms-btn danger" data-admin-logout>Cerrar panel</button></div>`;
function table(headers,rows){return `<div class="cms-table"><div class="cms-tr cms-th">${headers.map(x=>`<span>${x}</span>`).join('')}</div>${rows.join('')}</div>`}
function renderAdmin(name){
  if(!sessionStorage.getItem('kitsune-admin')){go('admin-access');return}
  if(name==='Resumen'){adminDash.innerHTML=adminHome;return}
  if(name==='Contenido')adminDash.innerHTML=head(name)+`<div class="cms-actions"><input id="newTitle" placeholder="Nombre de la nueva serie"><button class="cms-btn" data-add-content>＋ Crear anime</button></div>`+table(['Título','Estado','Acciones'],adminStore.content.map((x,i)=>`<div class="cms-tr"><b>${x[0]}</b><span class="cms-status">${x[1]}</span><span><button class="mini" data-publish="${i}">Publicar</button><button class="mini danger" data-delete-content="${i}">Eliminar</button></span></div>`));
  if(name==='Episodios')adminDash.innerHTML=head(name)+`<div class="cms-card"><h2>Nuevo episodio</h2><div class="cms-form"><input id="episodeAnime" placeholder="Serie"><input id="episodeNumber" type="number" min="1" placeholder="N.º episodio"><input id="episodeTitle" placeholder="Título"><button class="cms-btn" data-add-episode>Crear y enviar a procesamiento</button></div></div>`+table(['Episodio','Serie','Estado'],[`<div class="cms-tr"><b>El cielo recuerda</b><span>Astral Edge · E01</span><span class="cms-status">Publicado</span></div>`,`<div class="cms-tr"><b>Tráiler temporada 3</b><span>Mushoku Tensei</span><span class="cms-status">Publicado</span></div>`]);
  if(name==='Usuarios')adminDash.innerHTML=head(name)+table(['Usuario','Rol','Estado / Acciones'],adminStore.users.map((x,i)=>`<div class="cms-tr"><b>${x[0]}</b><select data-user-role="${i}"><option ${x[1]==='Usuario'?'selected':''}>Usuario</option><option ${x[1]==='Programador'?'selected':''}>Programador</option><option ${x[1]==='Administrador'?'selected':''}>Administrador</option></select><span><i class="cms-status">${x[2]}</i><button class="mini danger" data-block-user="${i}">${x[2]==='Activo'?'Bloquear':'Activar'}</button></span></div>`));
  if(name==='Procesamiento')adminDash.innerHTML=head(name)+`<div class="cms-actions"><button class="cms-btn" data-process-all>▶ Procesar toda la cola</button></div>`+table(['Archivo','Estado','Progreso / Acción'],adminStore.jobs.map((x,i)=>`<div class="cms-tr"><b>${x[0]}</b><span class="cms-status">${x[1]}</span><span>${x[2]} <button class="mini" data-retry="${i}">Reintentar</button></span></div>`));
  if(name==='Auditoría')adminDash.innerHTML=head(name)+table(['Evento','Responsable','Fecha'],adminStore.logs.map(x=>`<div class="cms-tr"><b>${x[0]}</b><span>${x[1]}</span><span>${x[2]}</span></div>`));
}
adminSide.querySelectorAll('a').forEach(a=>a.onclick=()=>{adminSide.querySelectorAll('a').forEach(x=>x.classList.remove('on'));a.classList.add('on');renderAdmin(a.textContent)});
document.addEventListener('click',e=>{const b=e.target.closest('[data-admin-logout],[data-add-content],[data-add-episode],[data-publish],[data-delete-content],[data-block-user],[data-process-all],[data-retry]');if(!b)return;if(b.hasAttribute('data-admin-logout')){sessionStorage.removeItem('kitsune-admin');go('catalogo');return}if(b.hasAttribute('data-add-content')){const v=document.querySelector('#newTitle').value.trim();if(v){adminStore.content.unshift([v,'Borrador']);adminStore.logs.unshift([`Creación de ${v}`,'ADMIN','Ahora']);saveAdmin();renderAdmin('Contenido')}}if(b.dataset.publish!==undefined){adminStore.content[b.dataset.publish][1]='Publicado';saveAdmin();renderAdmin('Contenido')}if(b.dataset.deleteContent!==undefined){adminStore.content.splice(b.dataset.deleteContent,1);saveAdmin();renderAdmin('Contenido')}if(b.dataset.blockUser!==undefined){let u=adminStore.users[b.dataset.blockUser];u[2]=u[2]==='Activo'?'Bloqueado':'Activo';saveAdmin();renderAdmin('Usuarios')}if(b.hasAttribute('data-process-all')){adminStore.jobs.forEach(j=>{j[1]='Completado';j[2]='100%'});saveAdmin();renderAdmin('Procesamiento')}if(b.dataset.retry!==undefined){adminStore.jobs[b.dataset.retry][1]='Procesando';adminStore.jobs[b.dataset.retry][2]='25%';saveAdmin();renderAdmin('Procesamiento')}if(b.hasAttribute('data-add-episode')){const s=document.querySelector('#episodeAnime').value.trim(),n=document.querySelector('#episodeNumber').value,t=document.querySelector('#episodeTitle').value.trim();if(s&&n&&t){adminStore.jobs.unshift([`${s.toLowerCase().replaceAll(' ','-')}-e${n}.mp4`,'En cola','0%']);saveAdmin();renderAdmin('Procesamiento')}}});
document.addEventListener('change',e=>{if(e.target.dataset.userRole!==undefined){adminStore.users[e.target.dataset.userRole][1]=e.target.value;saveAdmin()}});
